/**
 * Code Generator - AST to C++
 *
 * Converts Abstract Syntax Tree (from BlockDiagramCompiler) into
 * complete C++ firmware code ready for compilation and deployment.
 *
 * Supports:
 * - Arduino (Uno, Mega, Nano)
 * - STM32 (F103, F401, L476)
 * - ESP32 (DevKitC)
 */

import { CompiledAst, Variable, Statement } from './BlockDiagramCompiler';

/**
 * Generated C++ code output
 */
export interface GeneratedCode {
  mainCode: string;        // Complete main.cpp with all code
  platformioIni: string;   // platformio.ini for build configuration
  projectName: string;
  targetBoard: string;
  files: {
    'src/main.cpp': string;
    'platformio.ini': string;
    'README.md': string;
  };
}

/**
 * Code generator for converting AST to C++ firmware
 */
export class CodeGenerator {
  /**
   * Generate complete C++ firmware from AST
   */
  static generate(
    ast: CompiledAst,
    target: string,
    projectName: string = 'firmware_project'
  ): GeneratedCode {
    const mainCode = this.generateMainCpp(ast, target, projectName);
    const platformioIni = this.generatePlatformioIni(target, projectName);
    const readme = this.generateReadme(projectName, target);

    return {
      mainCode,
      platformioIni,
      projectName,
      targetBoard: target,
      files: {
        'src/main.cpp': mainCode,
        'platformio.ini': platformioIni,
        'README.md': readme,
      },
    };
  }

  /**
   * Generate main.cpp with all setup and loop code
   */
  private static generateMainCpp(
    ast: CompiledAst,
    target: string,
    projectName: string
  ): string {
    const lines: string[] = [];

    // Headers
    lines.push('/**');
    lines.push(` * ${projectName}`);
    lines.push(' * Auto-generated firmware from block diagram');
    lines.push(' * Generated by Tupan Microcontroller Simulator');
    lines.push(' */');
    lines.push('');

    // Includes
    for (const include of ast.includes) {
      lines.push(include);
    }
    lines.push('');

    // Defines (preprocessor macros)
    if (Object.keys(ast.defines).length > 0) {
      lines.push('// ========== Configuration Defines ==========');
      for (const [key, value] of Object.entries(ast.defines)) {
        lines.push(`#define ${key} ${value}`);
      }
      lines.push('');
    }

    // Global Variables
    if (ast.globalVariables.length > 0) {
      lines.push('// ========== Global Variables ==========');
      for (const variable of ast.globalVariables) {
        const initialValue = variable.initialValue ? ` = ${variable.initialValue}` : '';
        const arrayDecl = variable.isArray ? `[${variable.arraySize || 10}]` : '';
        lines.push(`${variable.type} ${variable.name}${arrayDecl}${initialValue};`);
      }
      lines.push('');
    }

    // Functions
    if (ast.functions.length > 0) {
      lines.push('// ========== Function Definitions ==========');
      for (const func of ast.functions) {
        // Function signature
        const params = func.parameters
          .map(p => `${p.type} ${p.name}`)
          .join(', ');
        lines.push(`${func.returnType} ${func.name}(${params}) {`);

        // Function body
        for (const stmt of func.body) {
          const indent = '  '.repeat(stmt.indent + 1);
          lines.push(`${indent}${stmt.code}`);
        }

        lines.push('}');
        lines.push('');
      }
    }

    // Setup function
    lines.push('// ========== Arduino Setup ==========');
    lines.push('void setup() {');
    lines.push('  // Initialize serial communication');
    lines.push('  Serial.begin(9600);');
    lines.push('');

    lines.push('  // Block diagram initialization');
    for (const stmt of ast.setupStatements) {
      const indent = '  '.repeat(stmt.indent + 1);
      lines.push(`${indent}${stmt.code}`);
    }

    lines.push('}');
    lines.push('');

    // Loop function
    lines.push('// ========== Arduino Loop ==========');
    lines.push('void loop() {');

    if (ast.loopStatements.length === 0) {
      lines.push('  // Main execution loop');
      lines.push('  delay(10);  // Placeholder loop body');
    } else {
      for (const stmt of ast.loopStatements) {
        const indent = '  '.repeat(stmt.indent + 1);
        lines.push(`${indent}${stmt.code}`);
      }
    }

    lines.push('}');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Generate platformio.ini configuration file
   */
  private static generatePlatformioIni(target: string, projectName: string): string {
    const boardMap: Record<string, { platform: string; board: string; framework: string }> = {
      arduino: {
        platform: 'atmelavr',
        board: 'uno',
        framework: 'arduino',
      },
      arduinomega: {
        platform: 'atmelavr',
        board: 'megaatmega2560',
        framework: 'arduino',
      },
      stm32f103: {
        platform: 'ststm32',
        board: 'bluepill_f103c8',
        framework: 'arduino',
      },
      stm32f401: {
        platform: 'ststm32',
        board: 'discovery_f407vg',
        framework: 'arduino',
      },
      stm32l476: {
        platform: 'ststm32',
        board: 'nucleo_l476rg',
        framework: 'arduino',
      },
      esp32: {
        platform: 'espressif32',
        board: 'esp32doit-devkit-v1',
        framework: 'arduino',
      },
    };

    const config = boardMap[target.toLowerCase()] || boardMap.arduino;

    const lines: string[] = [];
    lines.push(`[env:${projectName}]`);
    lines.push(`platform = ${config.platform}`);
    lines.push(`board = ${config.board}`);
    lines.push(`framework = ${config.framework}`);
    lines.push('upload_speed = 115200');
    lines.push('monitor_speed = 9600');
    lines.push('lib_deps =');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Generate README.md with project documentation
   */
  private static generateReadme(projectName: string, target: string): string {
    const lines: string[] = [];

    lines.push(`# ${projectName}`);
    lines.push('');
    lines.push('Auto-generated firmware project from Tupan Block Diagram Compiler');
    lines.push('');

    lines.push('## Target Platform');
    lines.push(`- **Board:** ${target}`);
    lines.push('- **Framework:** Arduino');
    lines.push('');

    lines.push('## Building and Uploading');
    lines.push('');
    lines.push('### Using PlatformIO CLI:');
    lines.push('```bash');
    lines.push('# Build the project');
    lines.push('platformio run');
    lines.push('');
    lines.push('# Upload to device');
    lines.push('platformio run --target upload');
    lines.push('');
    lines.push('# Monitor serial output');
    lines.push('platformio device monitor');
    lines.push('```');
    lines.push('');

    lines.push('### Using PlatformIO IDE:');
    lines.push('1. Open this folder in PlatformIO IDE');
    lines.push('2. Click "Build" to compile');
    lines.push('3. Click "Upload" to flash the microcontroller');
    lines.push('4. Click "Monitor" to view serial output');
    lines.push('');

    lines.push('### Using Arduino IDE:');
    lines.push('1. Copy `src/main.cpp` content');
    lines.push('2. Create new sketch in Arduino IDE');
    lines.push('3. Paste the code');
    lines.push('4. Select your board from Tools → Board');
    lines.push('5. Click Upload');
    lines.push('');

    lines.push('## Project Structure');
    lines.push('');
    lines.push('```');
    lines.push('.');
    lines.push('├── src/');
    lines.push('│   └── main.cpp          # Main firmware code');
    lines.push('├── platformio.ini        # Build configuration');
    lines.push('└── README.md             # This file');
    lines.push('```');
    lines.push('');

    lines.push('## Generated Code Structure');
    lines.push('');
    lines.push('The generated code follows the standard Arduino structure:');
    lines.push('');
    lines.push('1. **Includes** - Required library headers');
    lines.push('2. **Defines** - Configuration macros');
    lines.push('3. **Global Variables** - Block state and configuration');
    lines.push('4. **Functions** - Block computation functions');
    lines.push('5. **setup()** - Hardware initialization');
    lines.push('6. **loop()** - Main execution loop');
    lines.push('');

    lines.push('## Troubleshooting');
    lines.push('');
    lines.push('### Compilation Errors');
    lines.push('- Ensure all required libraries are installed');
    lines.push('- Check that the correct board is selected in platformio.ini');
    lines.push('- Verify that all #include statements point to valid headers');
    lines.push('');

    lines.push('### Upload Issues');
    lines.push('- Check USB cable and connection');
    lines.push('- Verify COM port in platformio.ini (upload_port)');
    lines.push('- Reset the device before uploading');
    lines.push('');

    lines.push('### Runtime Issues');
    lines.push('- Use Serial.print() to debug variable values');
    lines.push('- Monitor the serial output at 9600 baud');
    lines.push('- Check memory usage (RAM may be limited on some boards)');
    lines.push('');

    lines.push('## Documentation');
    lines.push('');
    lines.push('- [PlatformIO Documentation](https://docs.platformio.org/)');
    lines.push('- [Arduino Language Reference](https://www.arduino.cc/reference/en/)');
    lines.push('- [Tupan Documentation](https://github.com/tupan-project)');
    lines.push('');

    lines.push('---');
    lines.push('Generated by Tupan Microcontroller Simulator');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Export project as downloadable files object
   */
  static exportAsFiles(generated: GeneratedCode): Record<string, string> {
    return generated.files;
  }

  /**
   * Format code with proper indentation and spacing
   */
  private static formatCode(code: string): string {
    const lines = code.split('\n');
    let indentLevel = 0;
    const formatted: string[] = [];

    for (const line of lines) {
      const trimmed = line.trim();

      // Skip empty lines
      if (trimmed === '') {
        formatted.push('');
        continue;
      }

      // Decrease indent for closing braces
      if (trimmed.startsWith('}')) {
        indentLevel = Math.max(0, indentLevel - 1);
      }

      // Add indented line
      const indent = '  '.repeat(indentLevel);
      formatted.push(`${indent}${trimmed}`);

      // Increase indent for opening braces
      if (trimmed.endsWith('{')) {
        indentLevel++;
      }
    }

    return formatted.join('\n');
  }
}
